addPaths();
gCoeffs = [1 0 0]; 
Npts = 50;
freq = 1;
addPaths();
a = -1;
b = 1;
[G, SPs_init, orders] = NSDeetsFromPoly(gCoeffs, 1e-16);
[contoursInSeq] = getSDtopology(G,SPs_init,sum(orders)+1,a,b,true,false,freq);
xlim([-5 5]);
ylim([-5 5]);
[z, w] = makeQuad(contoursInSeq, freq, Npts, G, NaN, [a b]);
hold on;
plot(z,'x');
hold off;